services:
  web:
    build: ./backend
    container_name: puzzle_backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
    build: ./backend
    container_name: puzzle_migrations
    env_file:
      - ./.env
    command: >
      sh -c "
        sleep 5;
        alembic upgrade head
      "
    depends_on:
      - db
  db:
    image: "postgres:16.3-alpine"
    container_name: puzzle_database
    env_file:
      - ./.env
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
    name: db_volume