"""Add color to Piece

Revision ID: 090fc2d1f143
Revises: 01f26f156d14
Create Date: 2024-07-08 19:07:24.846852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090fc2d1f143'
down_revision: Union[str, None] = '01f26f156d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('color', sa.Integer(), server_default='14531481', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'color')
    # ### end Alembic commands ###
