"""Add game-piece relationship

Revision ID: 382c668eb044
Revises: dbfb8168026e
Create Date: 2024-04-13 20:02:54.770001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382c668eb044'
down_revision: Union[str, None] = 'dbfb8168026e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamepieces',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'piece_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamepieces')
    # ### end Alembic commands ###
