"""Add piece

Revision ID: dbfb8168026e
Revises: 0f2a9677736f
Create Date: 2024-04-08 14:46:38.359710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfb8168026e'
down_revision: Union[str, None] = '0f2a9677736f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece',
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piece')
    # ### end Alembic commands ###
