"""Add Menu

Revision ID: 1f37e3800cd9
Revises: 81641f63833f
Create Date: 2024-08-24 02:39:40.192287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f37e3800cd9'
down_revision: Union[str, None] = '81641f63833f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
