"""Added note column to game

Revision ID: 6b4a0e0c1564
Revises: f7544c3ee252
Create Date: 2024-07-23 01:48:44.282436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4a0e0c1564'
down_revision: Union[str, None] = 'f7544c3ee252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('note', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'note')
    # ### end Alembic commands ###
