"""Add piece rotations

Revision ID: 76aa72d7165f
Revises: 382c668eb044
Create Date: 2024-04-14 15:30:45.839701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aa72d7165f'
down_revision: Union[str, None] = '382c668eb044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piecerotation',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piecerotation')
    # ### end Alembic commands ###
