"""Compressed 2024-08-12

Revision ID: 81641f63833
Revises: 
Create Date: 2024-08-12 21:11:18.326638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_users_db_sqlalchemy.generics import TIMESTAMPAware

# revision identifiers, used by Alembic.
revision: str = '81641f63833f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('title', sa.String(), server_default='', nullable=False),
    sa.Column('width', sa.SmallInteger(), nullable=False),
    sa.Column('height', sa.SmallInteger(), nullable=False),
    sa.Column('note', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('piece',
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.Integer(), server_default='14531481', nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece'))
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('accesstoken',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_accesstoken_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_accesstoken'))
    )
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    op.create_table('gamepieces',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('count', sa.SmallInteger(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_gamepieces_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], name=op.f('fk_gamepieces_piece_id_piece'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'piece_id', name=op.f('pk_gamepieces'))
    )
    op.create_table('piecerotation',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('flipped', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], name=op.f('fk_piecerotation_piece_id_piece'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piecerotation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piecerotation')
    op.drop_table('gamepieces')
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('piece')
    op.drop_table('game')
    # ### end Alembic commands ###
