"""Add flipped field to Rotation

Revision ID: 81641f63833f
Revises: 8ec43e574466
Create Date: 2024-08-12 00:07:46.345013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81641f63833f'
down_revision: Union[str, None] = '8ec43e574466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piecerotation', sa.Column('flipped', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE piecerotation SET flipped = -1")
    op.execute('UPDATE piecerotation SET flipped = 1 WHERE "order" IN (5, 6, 7, 8)')
    op.execute('UPDATE piecerotation SET flipped = 0 WHERE "order" IN (1, 2, 3, 4)')
    op.execute("""UPDATE piecerotation SET flipped = 1 WHERE "order" IN (3, 4) AND CAST(points AS jsonb) IN (jsonb('[[0, 0], [0, 1], [1, 0], [2, -1], [2, 0]]'), jsonb('[[0, 0], [1, 0], [1, 1], [1, 2], [2, 2]]'), jsonb('[[0, 0], [0, 1], [1, 1], [2, 1], [2, 2]]'), jsonb('[[0, 0], [1, -2], [1, -1], [1, 0], [2, -2]]'))""")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piecerotation', schema=None) as batch_op:
        batch_op.alter_column('flipped',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piecerotation', 'flipped')
    # ### end Alembic commands ###
