services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    env_file:
      - ./.env
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
    ports:
      - 443:443
      - 80:80
    networks:
      - puzzle
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
      - ./static:/var/www
    restart: unless-stopped

networks:
  puzzle:
    name: puzzle