services:
  web:
    image: ${BACKEND_IMAGE}
    container_name: puzzle_backend
    env_file:
      - ./.env
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped     
    networks:
      - puzzle
  migrations:
    image: ${BACKEND_IMAGE}
    container_name: puzzle_migrations
    env_file:
      - ./.env
    command: >
      sh -c "alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - puzzle
  db:
    image: "postgres:16.3-alpine"
    container_name: puzzle_database
    env_file:
      - ./.env
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - puzzle
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 3s
      timeout: 5s
      retries: 5
  nginx:
    image: ${FRONTEND_IMAGE}
    container_name: puzzle_nginx
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx-conf:/etc/nginx/conf.d
      - nginx_cache:/data/nginx/cache
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - puzzle

volumes:
  db_volume:
    name: db_volume
  nginx_cache:
    name: nginx_cache

networks:
  puzzle:
    name: puzzle
    external: true